# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOrganized' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'GoogleMaps', '~> 2.1'
  pod 'GooglePlaces'

  # Pods for iOrganized

end
